-- 1. Identity Store
CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. RBAC & Quota Controls
CREATE TABLE user_permissions (
    permission_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    role TEXT DEFAULT 'viewer',
    
    -- Administrative Controls
    can_manage_users BOOLEAN DEFAULT FALSE,
    can_view_audit_logs BOOLEAN DEFAULT FALSE,
    
    -- Media Controls
    can_upload_media BOOLEAN DEFAULT FALSE,
    can_delete_any_media BOOLEAN DEFAULT FALSE, -- If true, can delete others' files
    can_view_private_media BOOLEAN DEFAULT FALSE, -- Bypass access checks
    
    -- Resource Limits (Quotas)
    storage_limit_mb INT DEFAULT 100,
    
    CONSTRAINT fk_user
        FOREIGN KEY(user_id) 
        REFERENCES users(user_id)
        ON DELETE CASCADE
);

-- 3. Media Assets (The Protected Resources)
CREATE TABLE media_assets (
    asset_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uploaded_by BIGINT NOT NULL,
    file_path TEXT NOT NULL,
    file_size_mb DECIMAL(10,2) NOT NULL,
    
    -- Access Control Level
    access_level TEXT DEFAULT 'private', -- 'public', 'private', 'admin_only'
    created_at TIMESTAMPTZ DEFAULT NOW(),
    
    CONSTRAINT fk_uploader
        FOREIGN KEY(uploaded_by) 
        REFERENCES users(user_id)
        ON DELETE SET NULL
);